'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADRIFT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Adrift() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Adrift", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgAdd16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgAdd16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgALR16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgALR16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgALR32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgALR32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgArrangeHorz16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgArrangeHorz16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgArrangeVert16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgArrangeVert16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgAxes32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgAxes32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgBold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgBold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCancel16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCancel16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCancel32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCancel32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCascade16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCascade16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCentre16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCentre16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCentre32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCentre32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCharacter16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCharacter16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCharacter32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCharacter32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgChildren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgChildren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgColour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgColour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgCut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgCut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDelete32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDelete32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgDeveloper24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgDeveloper24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgEdit16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgEdit16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgEvent16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgEvent16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgEvent32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgEvent32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgExport16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgExport16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgExport32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgExport32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgExpression() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgExpression", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFindNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFindNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFolder16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFolder16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFolderBlue16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFolderBlue16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFolderClosed16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFolderClosed16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFolderClosedBlue16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFolderClosedBlue16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFolderList32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFolderList32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFontColour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFontColour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFunction16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFunction16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgFunction32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgFunction32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgGrid16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgGrid16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgGroup16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgGroup16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgGroup32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgGroup32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgHelp16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgHelp16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgHint16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgHint16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgHint32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgHint32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgImport16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgImport16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgImport32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgImport32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgIn48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgIn48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgItalic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgItalic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgKey16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgKey16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLocation16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLocation16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLocation32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLocation32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgLock32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgLock32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMap16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMap16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMap32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMap32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgNew16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgNew16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgNew32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgNew32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgObjectDynamic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgObjectDynamic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgObjectDynamic32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgObjectDynamic32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgObjectStatic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgObjectStatic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgObjectStatic32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgObjectStatic32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOneToOne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOneToOne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOpen16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOpen16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOpen32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOpen32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOptions16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOptions16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOptions32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOptions32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgOut48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgOut48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgParent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgParent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPaste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPaste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPause48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPause48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPauseShadow48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPauseShadow48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPlanView16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPlanView16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPlanView32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPlanView32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPlay48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPlay48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPlayer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPlayer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPlayShadow48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPlayShadow48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPrint16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPrint16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgPrint32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgPrint32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgProperty16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgProperty16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgProperty32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgProperty32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRefresh16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRefresh16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgReplace16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgReplace16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRun16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRun16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRun32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRun32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSave16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSave16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSave32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSave32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSaveAs32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSaveAs32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSettings16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSettings16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSettings32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSettings32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSpelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSpelling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgStop48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgStop48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgStopShadow48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgStopShadow48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSynonym16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSynonym16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgSynonym32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgSynonym32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskGeneral16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskGeneral16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskGeneral32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskGeneral32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskSpecific16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskSpecific16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskSpecific32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskSpecific32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskSystem16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskSystem16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTaskSystem32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTaskSystem32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTile16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTile16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgTimeEvent16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgTimeEvent16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgUnlock32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgUnlock32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgVariable16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgVariable16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgVariable32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgVariable32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgWarn16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgWarn16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgWarn32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgWarn32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgWeb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgWeb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgZoomIn16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgZoomIn16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgZoomIn32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgZoomIn32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgZoomOut16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgZoomOut16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgZoomOut32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgZoomOut32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Lydian() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Lydian", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenSelectedItemHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSelectedItemHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property player() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("player", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property taf() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("taf", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
