'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanelStatusBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelStatusBar As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtStatusBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LinkAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkAbout As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtUserStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanelAudioChannels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAudioChannels As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Channel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Channel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Channel8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''WebSplitter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Public WithEvents WebSplitter1 As Global.Infragistics.Web.UI.LayoutControls.WebSplitter

    '''<summary>
    '''UpdatePanelText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelText As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtOutputWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOutputWeb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''InputWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputWeb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtInputWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInputWeb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanelMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMap As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MapImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MapImage As Global.System.Web.UI.WebControls.Image
End Class
